# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/id_2026',
                'doc_host': 'https://dci-courses.github.io',
                'git_url': 'https://github.com/dci-courses/id_2026',
                'lib_path': 'id_2026'},
  'syms': {'id_2026.core': {'id_2026.core.foo': ('core.html#foo', 'id_2026/core.py')}}}
